/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "arraydatastore-test.check" instead.
 */

#include <check.h>

#line 1 "arraydatastore-test.check"
#include "arraydatastore.h"
#include "string.h"
START_TEST(ads_test_insert)
{
#line 4
  init(10);
  insert("El1");
  insert("El2");
  insert("El3");
  ck_assert_str_eq(get(1), "El1");
  ck_assert_str_eq(get(2), "El2");
  ck_assert_str_eq(get(3), "El3");
  ck_assert(get(4) == NULL);
}
END_TEST

START_TEST(ads_test_delete)
{
#line 13
  init(10);
  insert("El1");
  ck_assert_str_eq(get(1), "El1");
  delete("El1");
  ck_assert(get(1) == NULL);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, ads_test_insert);
    tcase_add_test(tc1_1, ads_test_delete);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
